### ISSUE TITLE
Recalc needs to affect all notes after preferences change (currently recalc only affects modified fields)

### ISSUE THREAD

**Issue by joestrong** [kaegi/MorphMan#177]
If you recalc, it only re-generates morphs for notes where the fields have been modified.

However, if the preferences are updated for something like the ignore brackets feature, a recalc needs to recalculate the morphs for notes containing brackets, even if the card hasn't been modified.

I suggest that recalc re-generate morphs for ALL notes, if the preferences have been changed.

**Comment by ianki** [comment]
This should now be supported with PR #194, if you enable the new option to rebuild the all.db in the UI.  Please try.

**Comment by joestrong** [comment]
I'm currently using Anki 2.1.26 (previous stable release), mainly because, ironically, the Arch repos don't currently provide 2.1.35.

I get the following errors on 2.1.26. Do we care about supporting the previous stable release?

```
morph/main.py:123:4: E1123: Unexpected keyword argument 'max' in method call (unexpected-keyword-arg)
morph/main.py:274:4: E1123: Unexpected keyword argument 'max' in method call (unexpected-keyword-arg)
```

If I remove the max attribute however, the feature seems to work well.

Also, do we want to have an option in the settings for this feature? I would have thought this is expected behaviour by the end user (I would assume changing my preferences and recalc would affect everything naturally). Extra options in the interface adds a little more complication. Intersted know what you think.

**Comment by ianki** [comment]
We can try to support the previous release, assuming other major features are still working.

Your K number going down could be if you have deleted cards, or if you introduced external morphs at some point, since only active cards will get processed.  That's the reason I made this change an option instead of rebuilding all.db by default.

What I was thinking is we could try to re-process the entries in the database instead of re-building from scratch.  The fields that come from old Anki notes get saved in the database.  However some challenges to this is that the original text from external sources don't get saved, and also the desired morphemizer setting used at the time is not saved.

**Comment by ianki** [comment]
Come to think of it, I may change it so that Anki cards get re-processed by default since we have full data, and other database entries just get left unchanged.

**Comment by ianki** [comment]
Could you try latest with the fixes in #196 ?

**Comment by joestrong** [comment]
It appears to work, and recalc seems to be really fast now which is really good!

I have just noticed a "bug" perhaps, but I think it's unrelated to this issue. When changing the brackets setting and run recalc, my known morphs numbers change. I think this is where brackets appear in cards marked as "known". Is there a separate db for known morphs, or is it always sourced from the cards?

**Comment by ianki** [comment]
The known.db is re-calculated from your cards, so if you block out brackets it makes sense for those morphs to disappear.

If you want to persist morphemes that aren't in your deck, you have the option of copying them to an "external.db".  That said I don't recommend it, since if at any point you want to switch to a different / better dictionary option you will have no way to really upgrade your "external.db".  Personally I have a deck that I just add cards with already known words to (and suspend them).

**Comment by ianki** [comment]
You can if you want, keep a doc like "external.txt" and then export that to "external.db" with the database manager whenever you add new things.  If you keep the "external.txt" then you can recreate things later on if you have to.

**Comment by ianki** [comment]
I think this is resolved now.
