### ISSUE TITLE
How can I change the status 'unknow'?

### ISSUE THREAD

**Issue by Ni-Go** [kaegi/MorphMan#31]
Hello! How are you? I recently found out about this great tool! Currently I am learning English, my native language is Spanish, I followed all the steps and apparently the addon worked correctly, the only inconvenience I have is that the words are not grouped by "seen", "know", "mature", This is how my database looks like:

https://imgur.com/a/I5VBrQq

How do I make 'unknown' not appear?

I thank you for your attention!

regards

**Comment by kaegi** [comment]
The `UNKNOWN` inside the database is additional information from the morphemizer, it has nothing to do with `seen`, `know`, `mature`. It could be something like `going verb gerund` instead of `going UNKNOWN UNKNOWN`. Because you use the general `space-morphemizer` no information is available. I don't think it is used anywhere... 

`seen`, `known`, `mature` are saved into different databases like `known.db`.

**Comment by kaegi** [comment]
If a morpheme/word is in a card that has an Anki interval of 21 days it is considered mature (meaning you could remember it for at least 21 days) and also saved into the mature database.
In a sentence that you know all word/morphemes except one, the focus morph (the morpheme you should focus on) is the one unknown morpheme. (It might be that focus morph is the single *unmature* morpheme between mature morphemes; I don't remember).
I do not remember if there is difference between `known` and `seen`... (the limit for known might be so low that every `seen` morpheme is automatically `known`)

The sequence is something like this (not exactly sure which order): all -> seen -> known -> mature

You can change in the general tab how you'd like MorphMan to treat the different phases in your learning process (if you want see the same morpheme in different context or if you want to learn a new word in every new card).
