### ISSUE TITLE
Separate different languages

### ISSUE THREAD

**Issue by IllIIIllI** [kaegi/MorphMan#52]
# This issue raises two sub-features:

## 1. Changing the Known Morph count so that it separates different languages. 

For example, if one were to be learning Japanese, French and Latin at the same time, this would involve separating say, Japanese vocabulary from Latin and French vocabulary. In other words, if one has 2000 known Japanese morphs, and 400 known Latin morphs, it would not display 

> K 2400

 but display two separate K values, maybe something like

> K 2000
> K 400

## 2. The same word from different languages aren't marked as known.

This is especially useful if the said words are false friends, such as:
* anus in Latin and English
* 丈夫 in Chinese and Japanese.

These should not be treated as the same word.

**Comment by shanrauf** [comment]
The main parsers that Morphman has are Japanese, Chinese, and languages with spaces, so if we were to separate K values, it would probably only be possible to separate based on which of the language parsers a user is using. That means that it would only work to separate K values for Chinese and Japanese for example (because they use different parsers and we could separate by parsers), but if you are studying Latin and French, they both use the same parser and so we wouldn't be able to separate those, unless we made a way for users to declare what language an Anki deck is for (but that seems excessive_. A simple solution, which I do for Japanese and Spanish, is have one profile per language.
