### ISSUE TITLE
Languages w/Spaces - Regex Suggestion

### ISSUE THREAD

**Issue by cofinley** [kaegi/MorphMan#55]
Hello,

First off: love the addon, lot of good work went into this.

I'm using it for French right now and I've noticed a small issue with the "languages w/spaces" morphemizer and thought I'd bring it up.

The [regex](https://github.com/kaegi/MorphMan/blob/master/morph/morphemizer.py#L290) to morphemize expressions in languages with spaces seems to miss some things, at least in French.

Example (focus morph in green):

![](https://i.imgur.com/7N6GsNM.png)

As you can see, the focus morph is cut off on the liasoned word. I'd expect the focus morph to be on the whole `quelqu'un` word instead of just `quelqu` since that's an incomplete word.

The regex `\w+` might be too simple. A regex like `\b[^\s\d]+\b` might work better. It would keep things together as long as the expression starts and ends with a word character.

I realize there are other languages that might have conflicting rules, so a test suite might help narrow down a better alternative. Either that or allowing users to specify and save a custom regex pattern if they are using a language with spaces.

For your consideration...

**Comment by shanrauf** [comment]
@cofinley  A test suite is definitely a good idea, and I've tried setting that up multiple times, but I can't get it working. The issue is that Anki addons import a lot of files directly from Anki's source code, and those files are only available when you run Anki, whereas when I try running unit tests separately outside of Anki, they fail because they can't find the Anki imports. If someone could get the unittest infrastructure setup, then I would be able to write tests and add this regex feature, but I don't know how to do it...

**Comment by izik1** [comment]
What one would have to do (and I'm not saying this a good or bad idea) is to separate the code being unit tested from anki, or mock up anki types (or some combination of both)

**Comment by shanrauf** [comment]
@izik1 Right, these were my thoughts exactly. Decoupling the Anki code with the rest of the addon sounds like a ton of work, and I don't know how to mock Anki types. Another thing that I have tried is downloading Anki from Github and adding it into the addon's directory so that the imports exist, but I could only get that somewhat working - that is probably the best option (can create a script to clone the repository from dae/Anki) but as of right now I can't get it working.

**Comment by izik1** [comment]
I'm out of town atm, but when I get back I could see if I could try adding a trivial test somewhere
