### ISSUE TITLE
Vietnamese support

### ISSUE THREAD

**Issue by BigUncleKerch** [kaegi/MorphMan#88]
Hi could anyone tell me how I can get this to work with the Vietnamese language. Please I’m willing to pay.

**Comment by shanrauf** [comment]
Doesn't Vietnamese have spaces? Use the Language with Spaces parser.

**Comment by BigUncleKerch** [comment]
> Doesn't Vietnamese have spaces? Use the Language with Spaces parser.

Vietnamese has spaces however one word in Vietnamese can be separated by a space. For example, the word "sun" in vietnamese is mặt trời. Therefore language and spaces parser wouldn't work as it would detect mặt and trời as two different words. Moreover, Morphman at the moment can not recognize Vietnamese diacritic characters so it would only recognize morph without diacritics e.g. mặt > m and t. Another person had this same issue here https://github.com/kaegi/MorphMan/issues/8 I tried following the instructions but couldn't get it to work.

anyhelp would be greatly appreciated.

**Comment by kurtisc** [comment]
I've created a fork that uses [pyvi](https://github.com/trungtv/pyvi) as a new morphemizer for Vietnamese sentences:
https://github.com/kurtisc/MorphMan

It's not suitable for a pull request because it relies on Anki being able to import pyvi. The only way I got that to work was by building Anki from scratch with pyvi in the Python requirements. Additionally, the HEAD of Anki seems to be incompatible with the HEAD of MorphMan, so my forks of both are based on an older version. if you're able and willing to build using this tree from scratch, it should perform better than Language w/ Spaces:
https://github.com/kurtisc/anki/tree/MorphMan-Viet
(I've only tested it on Ubuntu)

The Jieba morphemizer works by bundling Jieba with MorphMan. AFAICT that won't work for pyvi because it has big packages like Numpy as a dependency that would also need to be bundled and edited so their imports resolve correctly. Ideally there would be a segmentation library with few dependencies like Jieba for Vietnamese - or at least a GPLd corpus with word frequencies - but I wasn't able to find anything.

There's also an [old Reddit thread](https://www.reddit.com/r/Anki/comments/agfrc8/running_anki_through_virtualenv_to_access_pip/ee6b9ur/) that has instructions on running Anki from within a virtualenv but ```which anki``` results in an x86 binary on my machine, so it didn't work for me.

I'm open for suggestions on how to make this work 'out of the box' to get it upstream.

**Comment by BigUncleKerch** [comment]
Hey Kurtisc,

Thanks for your all the work. It's really appreciated!

**Comment by smartlitchi** [comment]
@kurtisc Have you found a way to bundle the vietnamese morphemizer ? I am really interested.

**Comment by kurtisc** [comment]
@smartlitchi Hello,

I haven't done any more work on bundling it. I experimented with a way of installing it within the app but decided not to pursue it since it wouldn't work on every platform. You can see that here:
https://github.com/kurtisc/MorphMan/tree/experimental-languages

The way it currently works is by appearing only if pyvi is importable. So I can install pyvi in a virtualenv, launch Anki from there and run MorphMan, then use its output in versions of Anki that don't have the patch or the importable pyvi. This is something I do now for myself, although I don't regularly update it to the newest version.

So, if you can get it to run by building yourself, you should be able to use it. I haven't seen any updates on the pull request though.

**Comment by sedosido** [comment]
I’m not really sure how to run a virtualenv or use a binary package (the link on the fork goes to the old anki forum). Do you have any advice or other links on how I can get it working? I have a basic understanding of code but I don’t understand dependencies or homebrew or anything like that very well.

Would it be possible to develop Vietnamese parsing as a second anki addon that vietnamese learners could install? Morphman has really revolutionised my ability to learn languages and I’d definitely be willing to try and figure out how to develop something like that myself.
