### ISSUE TITLE
Training morphman for seperate vocab entries

### ISSUE THREAD

**Issue by Hsys7272** [kaegi/MorphMan#92]
A sample would be: https://jisho.org/search/%E5%88%86
分 has three entries, ぶん, ふん, ぶ. All of which are inside of JLPT

On a similar note, can subs2srs parse this well?

**Comment by NinKenDo64** [comment]
I don't want to speak for the maintainer, but posting multiple issues just because your rather vague request hasn't been answered in the space of a few days will hardly endear the maintainer toward implementing what you want.

**Comment by Hsys7272** [comment]
> 
> 
> I don't want to speak for the maintainer, but posting multiple issues just because your rather vague request hasn't been answered in the space of a few days will hardly endear the maintainer toward implementing what you want.

You're actually right, might be better if i just delete this one and stick to MorphMan21 instead

**Comment by shanrauf** [comment]
@Hsys7272  I currently don't know how to have Morphman be able to distinguish between different readings of 分. Morphman uses a Japanese parser called Mecab, and so parsing errors like with 分 are due to the parser we are using, not necessarily Morphman. The parser could probably be improved, but it's tough.
